name: my first action
on: push

jobs: 

    buildjob: 
        runs-on: ubuntu-latest
        steps: 
        - name: action repo
          uses: actions/checkout@v4
       
        - name: list repofiles
          run: ls -ltra
        - name: executing shell script
          run: ./ascii_file.sh
        
        # name: message my name
        #  run: echo "my name is lewis"
        # name: listfiles
         # run: ls -ltra
        #- name: readfiles
        #  run: cat README.md
         