name: my first action
on: push

jobs: 

    buildjob: 
        runs-on: ubuntu-latest
        steps: 
        - name: action repo
          uses: actions/checkout@v4
        - name: readfiles/message
          run: |
           sudo apt-get install ansible -y
           echo "my name is lewis"
           ls -ltra
           cat README.md
        
        # name: message my name
        #  run: echo "my name is lewis"
        # name: listfiles
         # run: ls -ltra
        #- name: readfiles
        #  run: cat README.md
         