name: multiple deploy

on: push

jobs:
    build_1:
        
        runs-on: ubuntu-latest
        steps:
        - name: action repo
          uses: actions/checkout@v4

        

        - name: install cowsay
          run: sudo apt-get install cowsay -y

        - name: read the cmd
          run: cowsay -f dragon "run for your life-----raww" >> dragon.txt

        - name: upload artifact
          uses: actions/upload-artifact@v4
          with: 
            name: uploaded artifact
            path: dragon.txt
          

          

    Test-1:
        needs: build_1
        runs-on: ubuntu-latest

        steps:

        - name: download artifact
          uses: actions/download-artifact@v4
          with: 
            name: download dragon
            path: dragon.txt


        - name: files stored
          run: grep -i "dragon" dragon.txt

        
            




          
          

    deploy-1:
        needs: Test-1
        runs-on: ubuntu-latest

        steps:

        - name: download deploy
          uses: actions/download-artifact@v4
          with:
            name: artifact deploy download
            

        - name: readfile
          run: |
           cat dragon.txt
           echo "deploying......."




          