name: exploring variables and secrets

on: push

env:
    CONTAINER_REGISTRY: Docker.io
    DOCKER_USERNAME: lewisacid
    DOCKER_IMAGENAME: github-actions-ngnix

jobs:

    docker:
        runs-on: ubuntu-latest

        steps:
        - name: docker build
          run: docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$DOCKER_IMAGENAME:latest .

        - name: Docker Login
          env:
            docker_password: lewisacid@11223
          run: echo docker login --username=$DOCKER_USERNAME --password=$docker_password

        - name: docker publish
          run: echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$DOCKER_IMAGENAME:latest .

        
        

        

