name: exploring variables and secrets

on: push

env:
    CONTAINER_REGISTRY: docker.io
    DOCKER_USERNAME: lewisacid
    IMAGE_NAME: github-actions-nginx

jobs:

    docker:
        runs-on: ubuntu-latest

        steps:

        

        - name: List files (debug)
          run: ls -la
        - name: Docker build
          run: docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$DOCKER_IMAGENAME:latest .

        - name: Docker Login
          env:
            Docker_password: lewisacid@11223
          run: echo Docker login --username=$DOCKER_USERNAME --password=$Docker_password

        - name: Docker publish
          run: echo Docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest .

        
        

        

