name: exploring variables and secrets

on: push

jobs:
    Docker:
        runs-on: ubuntu-latest
        steps:
        - name: docker build
          run: docker build -t docker.io/dockerUsername/imageName:latest.

        - name: docker login
          run: docker login --username=dockerUsername --password=s3crets

        - name: docker publish
          run: docker push docker.io/dockerUsername/imageName:latest.

    




    